name: Yaci CLI GraalVM native image build
#on:
#  push:
#    tags:
#      - 'v*'

on:
  push:
    branches:
      - ci
jobs:
  build:
    name: ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [ '22.2.0']
        os: [macos-latest,  windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build shell
        run: |
          export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
          ./gradlew clean build nativeCompile
#        if: runner.os != 'Windows'

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: yaci-cli-${{ matrix.os }}-${{ matrix.arch }}
          path: build/native/nativeCompile/yaci-cli
